# Generated by Django 3.2.5 on 2022-12-22 15:16

import dash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_name', models.CharField(max_length=30, verbose_name='Tourist name')),
                ('a2_age', models.IntegerField(validators=[dash.models.validate_a2], verbose_name='Age')),
                ('a3_gender', models.CharField(max_length=15, verbose_name='Gender2')),
            ],
        ),
    ]
