# Generated by Django 3.2.5 on 2022-12-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=30, verbose_name='Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_name', models.CharField(max_length=30, verbose_name='Tourist name')),
                ('a2_age', models.IntegerField(verbose_name='Age')),
                ('a3_gender', models.CharField(max_length=30, verbose_name='Gender')),
            ],
        ),
    ]
