# Generated by Django 3.2.5 on 2022-12-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBT_attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_attraction', models.CharField(max_length=15, verbose_name='CBT_attraction')),
            ],
        ),
        migrations.CreateModel(
            name='CBT_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_facility', models.CharField(max_length=15, verbose_name='CBT Facility')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=15, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=15, verbose_name='Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(max_length=15, verbose_name='Spot')),
                ('district2', models.CharField(max_length=15, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(max_length=30, verbose_name='Tour_type')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_interest', models.CharField(max_length=30, verbose_name='Travel_interest')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_season', models.CharField(max_length=15, verbose_name='Travel_season')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_package', models.CharField(max_length=15, verbose_name='Vacation package offers')),
            ],
        ),
        migrations.AlterField(
            model_name='sex',
            name='sex',
            field=models.CharField(max_length=15, verbose_name='Sex'),
        ),
    ]
